# Generated by Django 6.0.6 on 2026-07-07 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(default='Our story', max_length=80)),
                ('hero_heading', models.CharField(default='Built on reliability, one job at a time', max_length=160)),
                ('hero_intro', models.TextField(default='SP Facilities Management started with a simple idea: cleaning should be dependable, thorough, and easy to book. Years on, that same standard guides every job we take on — from a single home to a multi-site commercial contract.')),
                ('values_eyebrow', models.CharField(default='What drives us', max_length=80)),
                ('values_heading', models.CharField(default='Our values', max_length=160)),
                ('why_eyebrow', models.CharField(default='Why customers choose us', max_length=80)),
                ('why_heading', models.CharField(default='What makes us different', max_length=160)),
                ('why_body', models.TextField(default="Anyone can send someone with a mop. We send a trained crew with a checklist built for your exact space — whether that's a single bathroom or an entire aged care wing — and we follow up to make sure the job met your standard, not just ours.\n\nEvery booking starts with a free, no-obligation quote, so you know the price before we ever set foot on site.", help_text='Separate paragraphs with a blank line.')),
                ('cta_heading', models.CharField(default='Ready to work with a team you can rely on?', max_length=160)),
                ('cta_body', models.CharField(default='Get a free, no-obligation quote in minutes.', max_length=200)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
            },
        ),
        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=60)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'About Page — Stat',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutValueCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_key', models.CharField(choices=[('residential', 'Residential (house icon)'), ('commercial', 'Commercial (building icon)'), ('industrial', 'Building & Industrial (factory icon)'), ('hospitality', 'Hospitality & Kitchen (utensils icon)'), ('specialised', 'Specialised (sparkles icon)'), ('aged_care', 'Aged Care (heart icon)'), ('outdoor', 'Outdoor (leaf icon)'), ('other', 'Other (checkmark icon)')], default='sparkles', max_length=20)),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=220)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'About Page — Value Card',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('email_send_failed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(default="We're here to help", max_length=80)),
                ('hero_heading', models.CharField(default='Get in touch', max_length=160)),
                ('hero_intro', models.TextField(default='Questions about a service, or ready for a free quote? Reach out however suits you best.')),
                ('quote_prompt_text', models.CharField(default='Prefer a quote instead?', help_text="Shown next to a 'Use the quote form' link that opens the quote modal.", max_length=200)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Contact Page Content',
                'verbose_name_plural': 'Contact Page Content',
            },
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(default='Est. for the long haul — Australia-wide', max_length=120)),
                ('hero_heading_line1', models.CharField(default='Clean spaces.', max_length=80)),
                ('hero_heading_emphasis', models.CharField(default='Better', max_length=80)),
                ('hero_heading_line2_suffix', models.CharField(default='places.', max_length=40)),
                ('hero_lede', models.TextField(default="SP Facilities Management keeps homes, workplaces, and job sites running the way they should — properly maintained, properly documented, no shortcuts. Request a free quote and we'll write up the job before we start.")),
                ('hero_primary_cta_text', models.CharField(default='Request a Quote →', max_length=60)),
                ('hero_secondary_cta_text', models.CharField(default='See the Services', max_length=60)),
                ('hero_rating_text', models.CharField(default='4.9/5', max_length=20)),
                ('hero_job_card_number', models.CharField(default='#SPC-0417', max_length=40)),
                ('hero_job_card_service_line', models.CharField(default='Commercial Clean — Parramatta, NSW', max_length=120)),
                ('services_eyebrow', models.CharField(default='What we handle', max_length=80)),
                ('services_heading', models.CharField(default='Seven services. One crew you can call.', max_length=160)),
                ('services_body', models.TextField(default="Every job leaves with a signed checklist — no guessing what got done. Pick a service below to see the scope, or tell us the job and we'll match the service.")),
                ('about_eyebrow', models.CharField(default='Why SP Facilities Management', max_length=80)),
                ('about_heading', models.CharField(default='Run like a trade, not a call centre.', max_length=160)),
                ('about_body', models.TextField(default='We started as a small crew doing end-of-lease cleans and grew because clients kept the same people coming back — not a rotating roster of strangers. Every site gets a documented checklist, a named point of contact, and a crew that actually knows the building.')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('areas_eyebrow', models.CharField(default='Where we work', max_length=80)),
                ('areas_heading', models.CharField(default='Service areas', max_length=160)),
                ('areas_body', models.TextField(default="Check your suburb below. Not listed? Ask anyway — we're expanding routes monthly.")),
                ('gallery_eyebrow', models.CharField(default='Recent jobs', max_length=80)),
                ('gallery_heading', models.CharField(default='Our work', max_length=160)),
                ('gallery_body', models.TextField(default='A running log of finished jobs, filed by service type. Photos below are placeholders until real project photos are supplied.')),
                ('testimonials_eyebrow', models.CharField(default='Client notes', max_length=80)),
                ('testimonials_heading', models.CharField(default='What sites tell us', max_length=160)),
                ('contact_eyebrow', models.CharField(default='Get in touch', max_length=80)),
                ('contact_heading', models.CharField(default='Tell us the job.', max_length=160)),
                ('meta_title', models.CharField(blank=True, help_text='Leave blank to use the site default.', max_length=160)),
                ('meta_description', models.CharField(blank=True, help_text='Leave blank to use the site default.', max_length=300)),
            ],
            options={
                'verbose_name': 'Home Page Content',
                'verbose_name_plural': 'Home Page Content',
            },
        ),
        migrations.CreateModel(
            name='HomeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(help_text='e.g. 500+, 100%, 24h', max_length=20)),
                ('label', models.CharField(max_length=60)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Home Page — Stat',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeValuePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=240)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Home Page — Value Point',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OurWorkPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(default='Proof, not promises', max_length=80)),
                ('hero_heading', models.CharField(default='Our work', max_length=160)),
                ('hero_intro', models.TextField(default='A look at completed jobs across our service categories. Photos below are placeholders — real project photos will replace these once supplied.')),
                ('cta_heading', models.CharField(default='Want results like these?', max_length=160)),
                ('cta_body', models.CharField(default='Get a free, no-obligation quote for your space today.', max_length=200)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Our Work Page Content',
                'verbose_name_plural': 'Our Work Page Content',
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('company_name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_actioned', models.BooleanField(default=False)),
                ('email_send_failed', models.BooleanField(default=False, help_text='Set automatically if the owner notification email failed to send — check this submission manually.')),
            ],
            options={
                'verbose_name': 'Quote Request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(help_text="Used in the page URL, e.g. 'residential'.", max_length=140, unique=True)),
                ('icon_key', models.CharField(choices=[('residential', 'Residential (house icon)'), ('commercial', 'Commercial (building icon)'), ('industrial', 'Building & Industrial (factory icon)'), ('hospitality', 'Hospitality & Kitchen (utensils icon)'), ('specialised', 'Specialised (sparkles icon)'), ('aged_care', 'Aged Care (heart icon)'), ('outdoor', 'Outdoor (leaf icon)'), ('other', 'Other (checkmark icon)')], default='other', help_text='Controls which built-in icon/illustration is shown for this service.', max_length=20)),
                ('summary', models.CharField(help_text='Short one-line description shown on cards and lists.', max_length=240)),
                ('long_description', models.TextField(blank=True, help_text="Optional extra paragraph shown on this service's own detail page.")),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide this service from the site without deleting it.')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first.')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='e.g. Greater Sydney', max_length=120)),
                ('suburb', models.CharField(max_length=120)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'region', 'suburb'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAreasPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(default='Where we work', max_length=80)),
                ('hero_heading', models.CharField(default='Service areas across Australia', max_length=160)),
                ('hero_intro', models.TextField(default="We cover metro and surrounding regions nationwide. Don't see your suburb listed? Ask us anyway — we're always expanding coverage.")),
                ('areas_note', models.CharField(default='Suburb list shown is a sample of coverage — contact us to confirm servicing for your exact address.', max_length=200)),
                ('cta_heading', models.CharField(default='Check if we cover your area', max_length=160)),
                ('cta_body', models.CharField(default="Send us your suburb and we'll confirm availability along with your free quote.", max_length=200)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Service Areas Page Content',
                'verbose_name_plural': 'Service Areas Page Content',
            },
        ),
        migrations.CreateModel(
            name='ServicesPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(default='Full service breakdown', max_length=80)),
                ('hero_heading', models.CharField(default='Cleaning services for every space', max_length=160)),
                ('hero_intro', models.TextField(default="Seven categories, one accountable team. Explore what's included in each service below, or request a free quote for a custom combination.")),
                ('cta_heading', models.CharField(default='Not sure which service you need?', max_length=160)),
                ('cta_body', models.CharField(default="Tell us about the space and we'll recommend the right combination — free of charge.", max_length=200)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Services Page Content',
                'verbose_name_plural': 'Services Page Content',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='SP Facilities Management', max_length=120)),
                ('tagline', models.CharField(default='Clean Spaces. Better Places.', max_length=160)),
                ('phone_display', models.CharField(default='1300 000 000', max_length=40)),
                ('phone_tel', models.CharField(default='+611300000000', help_text='Digits only, with country code, for tel: links, e.g. +611300000000', max_length=40)),
                ('email', models.EmailField(default='info@spfacilitiesmgmt.com.au', max_length=254)),
                ('address', models.CharField(default='Suite 4, 120 Example Street, Sydney NSW 2000', max_length=200)),
                ('office_hours', models.CharField(default='Mon–Sat, 6am–7pm', max_length=120)),
                ('map_embed_src', models.URLField(default='https://www.google.com/maps?q=Sydney%20NSW&output=embed', help_text="The 'src' URL from a Google Maps embed iframe.", max_length=500)),
                ('footer_about_text', models.CharField(default='Servicing residential, commercial, industrial, hospitality, aged care and outdoor clients across Australia.', max_length=220)),
                ('footer_fine_print', models.CharField(default='Website content is placeholder copy pending final approval.', max_length=200)),
                ('default_meta_description', models.CharField(default='Professional residential, commercial, industrial, hospitality, aged care and outdoor cleaning services across Australia. Insured, reliable, and trusted. Get a free quote today.', help_text='Used as the fallback meta description on any page without its own.', max_length=300)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=120)),
                ('author_role', models.CharField(blank=True, help_text='e.g. Office Manager, Bright Point Offices', max_length=160)),
                ('quote', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrustBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(choices=[('home_strip', 'Homepage trust strip (under the hero)'), ('footer', 'Footer trust & compliance list')], max_length=20)),
                ('text', models.CharField(max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Trust Badge',
                'ordering': ['placement', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('alt_text', models.CharField(blank=True, help_text='Describes the photo for screen readers and SEO. Defaults to the title if left blank.', max_length=200)),
                ('placeholder_note', models.CharField(blank=True, help_text='Shown if no real image has been uploaded yet.', max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_images', to='core.service')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.service')),
            ],
            options={
                'verbose_name': 'Service Feature (sub-service)',
                'ordering': ['service', 'order', 'id'],
            },
        ),
    ]
